### ISSUE TITLE
Error training_generate_from_wf

### ISSUE THREAD

**Issue by willemdek11** [galaxyproject/training-material#1048]
Yesterday I tried the following code to auto-generate a tutorial, but got the following error.

```planemo training_generate_from_wf --topic_name "sequence-analysis" --tutorial_name "nanopore" --workflow ~/Downloads/Galaxy-Workflow-Nanopore_sequence_analysis.ga```

**Workflow:**
https://raw.githubusercontent.com/galaxyproject/training-material/9dddf6c292134bf74c8edf42cb6716735ad982fe/topics/sequence-analysis/tutorials/nanopore/workflows/Galaxy-Workflow-Nanopore_sequence_analysis.ga

**Error:**
```Traceback (most recent call last):
  File "/home/willlem/.venv/bin/planemo", line 11, in <module>
    sys.exit(planemo())
  File "/home/willlem/.venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/willlem/.venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/willlem/.venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/willlem/.venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/willlem/.venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/willlem/.venv/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/willlem/.venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/willlem/.venv/local/lib/python2.7/site-packages/planemo/cli.py", line 195, in handle_blended_options
    return f(*args, **kwds)
  File "/home/willlem/.venv/local/lib/python2.7/site-packages/planemo/commands/cmd_training_generate_from_wf.py", line 19, in cli
    training.generate_tuto_from_wf(ctx)
  File "/home/willlem/.venv/local/lib/python2.7/site-packages/planemo/training/__init__.py", line 86, in generate_tuto_from_wf
    self.check_topic_init_tuto()
  File "/home/willlem/.venv/local/lib/python2.7/site-packages/planemo/training/__init__.py", line 46, in check_topic_init_tuto
    self.topic.init_from_metadata()
  File "/home/willlem/.venv/local/lib/python2.7/site-packages/planemo/training/topic.py", line 120, in init_from_metadata
    ref.init_from_dict(r)
  File "/home/willlem/.venv/local/lib/python2.7/site-packages/planemo/training/utils.py", line 47, in init_from_dict
    self.summary = dict['summary']
KeyError: 'summary'```

**Comment by erasche** [comment]
Probably fixed in latest planemo
