### ISSUE TITLE
intersect step of tutorial Introduction to Genomics and Galaxy fails

### ISSUE THREAD

**Issue by cgirardot** [galaxyproject/training-material#1611]
Dear, 
trying to proceed through the Introduction to Genomics and Galaxy tutorial on `usegalaxy.eu`, the intersect tool fails with error :

```
Traceback (most recent call last):
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/intersect/33b3f3688db4/intersect/gops_intersect.py", line 100, in <module>
    main()
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/intersect/33b3f3688db4/intersect/gops_intersect.py", line 77, in main
    for feature in intersect( [g1, g2], pieces=pieces, mincols=mincols ):
  File "/opt/galaxy/venv/lib/python2.7/site-packages/bx/intervals/operations/intersect.py", line 23, in intersect
    bitsets = intersect[0].binned_bitsets( upstream_pad=upstream_pad, downstream_pad=downstream_pad, lens=lens )
  File "/opt/galaxy/venv/lib/python2.7/site-packages/bx/intervals/io.py", line 158, in binned_bitsets
    for interval in self:
  File "/opt/galaxy/venv/lib/python2.7/site-packages/six.py", line 564, in next
    return type(self).__next__(self)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/bx/intervals/io.py", line 227, in __next__
    rval = NiceReaderWrapper.next( self )
  File "/opt/galaxy/venv/lib/python2.7/site-packages/six.py", line 564, in next
    return type(self).__next__(self)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/bx/intervals/io.py", line 227, in __next__
    rval = NiceReaderWrapper.next( self )

[skipping hundreds ...]

  File "/opt/galaxy/venv/lib/python2.7/site-packages/bx/intervals/io.py", line 227, in __next__
    rval = NiceReaderWrapper.next( self )
  File "/opt/galaxy/venv/lib/python2.7/site-packages/six.py", line 564, in next
    return type(self).__next__(self)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/bx/intervals/io.py", line 227, in __next__
    rval = NiceReaderWrapper.next( self )
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

looks like a tool bug but it seems to be the same tool version 1.0.0...

<img width="1118" alt="Screenshot 2019-09-24 at 16 39 42" src="https://user-images.githubusercontent.com/10990795/65521729-fcb55800-dee9-11e9-84a4-0deb9c554d55.png">

**Comment by wm75** [comment]
This is on usegalaxy.eu, right?
In that case, see https://help.galaxyproject.org/t/problem-with-intersect-tool-tutorial/2147.
Try to switch to the older version of the tool.
