### ISSUE TITLE
Automated Videos currently failing

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/training-material#3234]
Just opening this to track the issue, since it's known.

```
Error: Cannot find module 'fonteditor-core'
Require stack:
- /home/runner/work/training-material/training-material/node_modules/.bin/decktape
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/runner/work/training-material/training-material/node_modules/.bin/decktape:7:19)
```

decktape is installed and it's dependency fonteditor-core. But it's still not finding it and I don't know why.

**Comment by shiltemann** [comment]
test started failing after merging this: https://github.com/galaxyproject/training-material/pull/3078
