### ISSUE TITLE
`bundle add webrick` needed for Jekyll on Ruby 3 (and thus Gitpod)

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/training-material#3582]
`make gitpod-serve` fails with current Gitpod because it is Gitpod these days is running off Ruby 3. The error message is:

```
/home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:179:in `require_relative'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:179:in `setup'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:100:in `process'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/bin/jekyll:25:in `load'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/bin/jekyll:25:in `<main>'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `eval'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `<main>'
make: *** [Makefile:76: serve-gitpod] Error 1
```

The solution to this error is a simple `bundle add webrick` (see the conversation [here](https://talk.jekyllrb.com/t/load-error-cannot-load-such-file-webrick/5417/2)). Its not clear to me if this should be added to the [Gemfile](https://github.com/galaxyproject/training-material/blob/main/Gemfile) (because it might break other versions of Ruby) or to the [.gitpod.yml](https://github.com/galaxyproject/training-material/blob/main/.gitpod.yml) or perhaps even to the [tutorial](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/gitpod/tutorial.html).

**Comment by martenson** [comment]
Adding webrick fixes it for me, thank you for figuring this out @pvanheus!

The underlying problem is well described here: https://github.com/jekyll/jekyll/issues/8523
