### ISSUE TITLE
"Can't find stylesheet to import." for first-time build with jekyll-sass-converter 3.0.0 

### ISSUE THREAD

**Issue by elichad** [galaxyproject/training-material#3805]
Following the [Jekyll tutorial](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/running-jekyll/tutorial.html), I encountered the error below.

Downgrading to `jekyll-sass-converter` version 2.x resolved the issue. 3.0.0 has some [breaking changes](https://github.com/jekyll/jekyll-sass-converter#migrate-from-2x-to-3x) but I couldn't figure out which one was causing this issue.

```
$ make serve-quick
find: ‘_site/training-material’: No such file or directory
find: ‘_site/training-material/*/*/slides/*’: No such file or directory
find: ‘_site/training-material’: No such file or directory
This will build the website with citations and other content disabled, and incremental on by default. To run the full preview (slower), use make serve

mv: cannot stat ‘Gemfile’: No such file or directory
mv: cannot stat ‘Gemfile.lock’: No such file or directory
Configuration file: /home/qci88181/training-material/_config.yml
Configuration file: /home/qci88181/training-material/_config-dev.yml
/home/qci88181/training-material/_plugins/notebook.rb:47: warning: key "fas fa-pencil-alt" is duplicated and overwritten on line 48
            Source: /home/qci88181/training-material
       Destination: /home/qci88181/training-material/_site/training-material
 Incremental build: enabled
      Generating... 
[GTN/API] Disabled
[GTN/Boxify]
[GTN/scholar] Creating global bib cache
[GTN/scholar] Done
[GTN/Notebooks] Rendering python ./topics/climate/tutorials/pangeo-notebook/tutorial.md
[GTN/MOD] Filling Time Cache
[GTN/Notebooks] Rendering bash ./topics/data-science/tutorials/cli-advanced/tutorial.md
[GTN/Notebooks] Rendering bash ./topics/data-science/tutorials/cli-bashcrawl/tutorial.md
[GTN/Notebooks] Rendering bash ./topics/data-science/tutorials/cli-basics/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-advanced-np-pd/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-basics-recap/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-basics/tutorial.md
[GTN/Notebooks] Rendering bash ./topics/data-science/tutorials/python-conda/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-exceptions/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-files/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-flow/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-functions/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-glob/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-iterables/tutorial.md
[GTN/Notebooks] Rendering bash ./topics/data-science/tutorials/python-linting/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-loops/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-math/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-multiprocessing/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-plotting/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-subprocess/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-testing/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-types/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/python-typing/tutorial.md
[GTN/Notebooks] Rendering bash ./topics/data-science/tutorials/python-venv/tutorial.md
[GTN/Notebooks] Rendering r ./topics/data-science/tutorials/r-dplyr/tutorial.md
[GTN/Notebooks] Rendering sql ./topics/data-science/tutorials/sql-advanced/tutorial.md
[GTN/Notebooks] Rendering sql ./topics/data-science/tutorials/sql-basic/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/sql-game/tutorial.md
[GTN/Notebooks] Rendering python ./topics/data-science/tutorials/sql-python/tutorial.md
[GTN/Notebooks] Rendering r ./topics/data-science/tutorials/sql-r/tutorial.md
[GTN/Notebooks] Rendering python ./topics/dev/tutorials/bioblend-api/tutorial.md
[GTN/Notebooks/R] Rendering RMarkdown ./topics/data-science/tutorials/r-dplyr/tutorial.Rmd
[GTN/Notebooks/R] Rendering RMarkdown ./topics/data-science/tutorials/sql-r/tutorial.Rmd
       Jekyll Feed: Generating feed for posts
Error: Can't find stylesheet to import.
    ╷
131 │ @import "assets/css/syntax_highlighting-dark.scss";
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  /home/qci88181/training-material/assets/css/main.scss 131:9  root stylesheet 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    Can't find stylesheet to import.
                    ------------------------------------------------
      Jekyll 4.3.1   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
Traceback (most recent call last):
        30: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/bin/jekyll:32:in `<main>'
        29: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/bin/jekyll:32:in `load'
        28: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/exe/jekyll:15:in `<top (required)>'
        27: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        26: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        25: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        24: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        23: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        22: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        21: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        20: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
        19: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        18: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:36:in `process'
        17: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:65:in `build'
        16: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/command.rb:28:in `process_site'
        15: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/site.rb:80:in `process'
        14: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/site.rb:211:in `render'
        13: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/site.rb:569:in `render_pages'
        12: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/site.rb:569:in `each'
        11: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/site.rb:570:in `block in render_pages'
        10: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/site.rb:578:in `render_regenerated'
         9: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:63:in `run'
         8: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:84:in `render_document'
         7: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:104:in `convert'
         6: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:104:in `reduce'
         5: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:104:in `each'
         4: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:105:in `block in convert'
         3: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:160:in `convert'
         2: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/sass-embedded-1.57.1-x86_64-linux-gnu/lib/sass/embedded.rb:47:in `compile_string'
         1: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/sass-embedded-1.57.1-x86_64-linux-gnu/lib/sass/embedded.rb:208:in `compile_string'
/home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/sass-embedded-1.57.1-x86_64-linux-gnu/lib/sass/embedded/protofier.rb:16:in `from_proto_compile_response': Can't find stylesheet to import. (Sass::CompileError)
        28: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/bin/jekyll:32:in `<main>'
        27: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/bin/jekyll:32:in `load'
        26: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/exe/jekyll:15:in `<top (required)>'
        25: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        24: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        23: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        22: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        21: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        20: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        19: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        18: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
        17: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        16: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:36:in `process'
        15: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:65:in `build'
        14: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/command.rb:28:in `process_site'
        13: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/site.rb:80:in `process'
        12: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/site.rb:211:in `render'
        11: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/site.rb:569:in `render_pages'
        10: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/site.rb:569:in `each'
         9: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/site.rb:570:in `block in render_pages'
         8: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/site.rb:578:in `render_regenerated'
         7: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:63:in `run'
         6: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:84:in `render_document'
         5: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:104:in `convert'
         4: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:104:in `reduce'
         3: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:104:in `each'
         2: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:105:in `block in convert'
         1: from /home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:159:in `convert'
/home/qci88181/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:175:in `rescue in convert': Can't find stylesheet to import. (Jekyll::Converters::Scss::SyntaxError)
make: *** [serve-quick] Error 1
```

**Comment by hexylena** [comment]
This should have been fixed in https://github.com/galaxyproject/training-material/pull/3796, can you check if you update the main branch/rebase against it?
