### ISSUE TITLE
make serve-quick fails on main

### ISSUE THREAD

**Issue by paulzierep** [galaxyproject/training-material#3967]
I just pulled the repo for the first time.

After:
```
make create-env
make install
make serve-quick
```

`make serve-quick` fails on main with:

```
Liquid Exception: undefined method `[]' for nil:NilClass in /home/paul/git/training-material/_layouts/faq-page.html
                    ------------------------------------------------
      Jekyll 4.3.2   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
Traceback (most recent call last):
        83: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/bin/jekyll:32:in `<main>'
        82: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/bin/jekyll:32:in `load'
        81: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
        80: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        79: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        78: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        77: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        76: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        75: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        74: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        73: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
        72: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        71: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
        70: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
        69: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
        68: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/site.rb:80:in `process'
        67: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/site.rb:211:in `render'
        66: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `render_pages'
        65: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `each'
        64: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/site.rb:564:in `block in render_pages'
        63: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/site.rb:572:in `render_regenerated'
        62: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:63:in `run'
        61: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:93:in `render_document'
        60: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:161:in `place_in_layouts'
        59: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:192:in `render_layout'
        58: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:129:in `render_liquid'
        57: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        56: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        55: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        54: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        53: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        52: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        51: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        50: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/template.rb:218:in `render!'
        49: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/template.rb:205:in `render'
        48: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/template.rb:240:in `with_profiling'
        47: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/template.rb:206:in `block in render'
        46: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/block_body.rb:82:in `render'
        45: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
        44: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/tags/for.rb:79:in `render'
        43: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/tags/for.rb:150:in `render_segment'
        42: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
        41: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/tags/for.rb:158:in `block in render_segment'
        40: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/tags/for.rb:158:in `each'
        39: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/tags/for.rb:160:in `block (2 levels) in render_segment'
        38: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/block_body.rb:91:in `render'
        37: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
        36: from /home/paul/git/training-material/_plugins/snippet.rb:45:in `render'
        35: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
        34: from /home/paul/git/training-material/_plugins/snippet.rb:47:in `block in render'
        33: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/inclusion.rb:16:in `render'
        32: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        31: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        30: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        29: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        28: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        27: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        26: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        25: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/template.rb:218:in `render!'
        24: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/template.rb:205:in `render'
        23: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/template.rb:240:in `with_profiling'
        22: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/template.rb:206:in `block in render'
        21: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/block_body.rb:91:in `render'
        20: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
        19: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/tags/assign.rb:26:in `render'
        18: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/variable.rb:82:in `render'
        17: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/variable.rb:82:in `inject'
        16: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/variable.rb:82:in `each'
        15: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/variable.rb:84:in `block in render'
        14: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/context.rb:86:in `invoke'
        13: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/liquid-4.0.4/lib/liquid/strainer.rb:56:in `invoke'
        12: from /home/paul/git/training-material/_plugins/jekyll-topic-filter.rb:567:in `topic_filter'
        11: from /home/paul/git/training-material/_plugins/jekyll-topic-filter.rb:25:in `topic_filter'
        10: from /home/paul/git/training-material/_plugins/jekyll-topic-filter.rb:17:in `fill_cache'
         9: from /home/paul/git/training-material/_plugins/jekyll-topic-filter.rb:17:in `each'
         8: from /home/paul/git/training-material/_plugins/jekyll-topic-filter.rb:18:in `block in fill_cache'
         7: from /home/paul/git/training-material/_plugins/jekyll-topic-filter.rb:403:in `filter_by_topic'
         6: from /home/paul/git/training-material/_plugins/jekyll-topic-filter.rb:384:in `process_pages'
         5: from /home/paul/git/training-material/_plugins/jekyll-topic-filter.rb:384:in `map'
         4: from /home/paul/git/training-material/_plugins/jekyll-topic-filter.rb:384:in `each'
         3: from /home/paul/git/training-material/_plugins/jekyll-topic-filter.rb:384:in `block in process_pages'
         2: from /home/paul/git/training-material/_plugins/jekyll-topic-filter.rb:314:in `resolve_material'
         1: from /home/paul/git/training-material/_plugins/jekyll-topic-filter.rb:314:in `map'
/home/paul/git/training-material/_plugins/jekyll-topic-filter.rb:326:in `block in resolve_material': undefined method `[]' for nil:NilClass (NoMethodError)
make: *** [Makefile:75: serve-quick] Error 1
```

`make serve` however works

**Comment by hexylena** [comment]
The commit is here https://github.com/galaxyproject/training-material/pull/3950/commits/a8ff3e70b47a3f1fd262ec10a448f32056b561ab if you want to cherry-pick it before I've got that PR merged.

**Comment by hexylena** [comment]
Perfect! The fix is merged into main, so, future PRs should fare better :)
