### ISSUE TITLE
make serve fails

### ISSUE THREAD

**Issue by paulzierep** [galaxyproject/training-material#4128]
I am on the main branch `make serve` fails with:
```
find: ‘_site/training-material’: No such file or directory
find: ‘_site/training-material/*/*/slides/*’: No such file or directory
find: ‘_site/training-material’: No such file or directory
Tip: Want faster builds? Use 'serve-quick' in place of 'serve'.
Tip: to serve in incremental mode (faster rebuilds), use the command: make serve FLAGS=--incremental

Configuration file: /home/paul/git/gtm/training-material/_config.yml
[GTN/Images] Could not load fastimage gem, disabling feature (probably due to conda) 
/home/paul/git/gtm/training-material/_plugins/gtn/images.rb:10: warning: already initialized constant FASTIMAGE_AVAILABLE
/home/paul/git/gtm/training-material/_plugins/gtn/images.rb:5: warning: previous definition of FASTIMAGE_AVAILABLE was here
[GTN] You are running 2.7.2 released on 2020-10-01 for x86_64-linux
[GTN] WARNING: This Ruby is pretty old, you might want to update.
            Source: /home/paul/git/gtm/training-material
       Destination: /home/paul/git/gtm/training-material/_site/training-material
 Incremental build: disabled. Enable with --incremental
      Generating... 
[GTN/SyntheticTopics] Generating Indexes
[GTN/SyntheticTopics] Creating covid19 topic
[GTN/scholar] Creating global bib cache
[GTN/scholar] Done: 955
[GTN/Sitemap] Generating
[GTN/MOD] Filling Time Cache
[GTN/API] Bibliography
Traceback (most recent call last):
        25: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/bin/jekyll:32:in `<main>'
        24: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/bin/jekyll:32:in `load'
        23: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
        22: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        21: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        20: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        19: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        18: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        17: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        16: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        15: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
        14: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        13: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
        12: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
        11: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
        10: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/site.rb:79:in `process'
         9: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/site.rb:191:in `generate'
         8: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/site.rb:191:in `each'
         7: from /home/paul/mambaforge/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.2/lib/jekyll/site.rb:193:in `block in generate'
         6: from /home/paul/git/gtm/training-material/_plugins/api.rb:128:in `generate'
         5: from /home/paul/git/gtm/training-material/_plugins/gtn/metrics.rb:146:in `generate_metrics'
         4: from /home/paul/git/gtm/training-material/_plugins/gtn/metrics.rb:146:in `map'
         3: from /home/paul/git/gtm/training-material/_plugins/gtn/metrics.rb:146:in `each'
         2: from /home/paul/git/gtm/training-material/_plugins/gtn/metrics.rb:150:in `block in generate_metrics'
         1: from /home/paul/git/gtm/training-material/_plugins/gtn/metrics.rb:150:in `each'
/home/paul/git/gtm/training-material/_plugins/gtn/metrics.rb:151:in `block (2 levels) in generate_metrics': undefined method `except' for {:value=>0, "layout"=>""}:Hash (NoMethodError)
make: *** [Makefile:67: serve] Error 1
```

**Comment by hexylena** [comment]
> [GTN] You are running 2.7.2 released on 2020-10-01 for x86_64-linux

It should be better if you update to a newer ruby, 3.0.0 and higher are known working.

**Comment by paulzierep** [comment]
thank you for the answer, you don't need to fix it for me now that I know the issue, maybe one could pin the version in the environment.yml if an old ruby is known to fail ?

**Comment by hexylena** [comment]
ahhh conda, I forgot about it. apologies. I use another method to manage ruby and associated dependencies
