### ISSUE TITLE
Failed serving website locally

### ISSUE THREAD

**Issue by timonschlegel** [galaxyproject/training-material#4990]
I'm trying to serve on a windows machine with WSL and ubuntu. The `make install` worked fine and only the `make serve(-quick)` failes with this message
```
$ make serve-quick
find: ‘_site/training-material’: No such file or directory
find: ‘_site/training-material/*/*/slides/*’: No such file or directory
find: ‘_site/training-material’: No such file or directory
This will build the website with citations and other content disabled, and incremental on by default. To run the full preview (slower), use make serve

mv: cannot stat 'Gemfile': No such file or directory
mv: cannot stat 'Gemfile.lock': No such file or directory
Configuration file: /mnt/c/Users/timon/Documents/training-material/_config.yml
Configuration file: /mnt/c/Users/timon/Documents/training-material/_config-dev.yml
[GTN] You are running 3.2.2 released on 2023-03-30 for x86_64-linux
            Source: /mnt/c/Users/timon/Documents/training-material
       Destination: /mnt/c/Users/timon/Documents/training-material/_site/training-material
 Incremental build: enabled
      Generating...
                    ------------------------------------------------
      Jekyll 4.3.3   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
/mnt/c/Users/timon/Documents/training-material/_plugins/gtn.rb:804:in `block in <top (required)>': undefined method `each' for "../CONTRIBUTORS.yaml":String (NoMethodError)

  site.data['contributors'].each do |name, contributor|
                           ^^^^^
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.3/lib/jekyll/hooks.rb:103:in `block in trigger'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.3/lib/jekyll/hooks.rb:102:in `each'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.3/lib/jekyll/hooks.rb:102:in `trigger'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.3/lib/jekyll/site.rb:183:in `read'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.3/lib/jekyll/site.rb:78:in `process'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.3/lib/jekyll/command.rb:28:in `process_site'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:65:in `build'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:36:in `process'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `each'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.3/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/gems/jekyll-4.3.3/exe/jekyll:15:in `<top (required)>'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/bin/jekyll:32:in `load'
        from /home/timonschlegel/miniconda3/envs/galaxy_training_material/share/rubygems/bin/jekyll:32:in `<main>'
make: *** [Makefile:78: serve-quick] Error 1
```

**Comment by hexylena** [comment]
Hi @timonschlegel if `site.data['contributors']` is returning `../CONTRIBUTORS.yaml`, then that probably means your filesystem does not support symlinks properly, or there is something odd around how it handles them.

You could resolve this one issue but I suspect more will arise shortly as we use symlinks in a number of places for metadata files.

The GTN does not officially support building on windows, you can try running it in GitPod as an alternative though? https://training.galaxyproject.org/training-material/topics/contributing/tutorials/gitpod/tutorial.html

**Comment by timonschlegel** [comment]
thank you for the quick response!
I've already used gitpod, but it is very slow. But since it works and there is no easy fix for my windows device, I'll use it

**Comment by hexylena** [comment]
We heard this complaint from others as well and aren't sure *why* it is so slow, it has been very difficult to debug unfortunately. I wish I had a better solution for you. Thanks for reporting it.
